[package]
name = "optitag"
version = "0.1.0"
edition = "2021"
authors = ["Micha≈Ç Sabiniarz <michal.sabiniarz@gmail.com>"]
description = "<placeholder> A simple directory tagger"
license = "MIT"

[dependencies]
